- name: Ensure bind9 is installed
  apt:
    name: bind9

- name: Copy named.conf.options file
  copy:
    src: files/named.conf.options
    dest: /etc/bind/
  notify: restart bind9

- name: Copy named.conf.local file
  copy:
    src: files/named.conf.local
    dest: /etc/bind/
  notify: restart bind9

- name: Copy db.example.com zone using template
  template:
    src: templates/db.example.com.j2
    dest: /var/cache/bind/db.example.com
  notify: restart bind9