- name: Create cephuser user
  user:
    name: cephuser
    create_home: yes
    shell: /bin/bash

- name: Allow cephuser to execute sudo commands without password
  lineinfile:
    path: /etc/sudoers
    line: 'cephuser ALL=(ALL) NOPASSWD:ALL'

- name: Create .ssh structure
  file:
    path: /home/cephuser/.ssh
    state: directory
    owner: cephuser
    group: cephuser
    mode: 0700

- name: Copy ansible_rsa private key
  copy:
    src: files/ansible_rsa
    dest: /home/cephuser/.ssh/id_rsa
    owner: cephuser
    group: cephuser
    mode: 0600

- name: Copy ansible_rsa public key
  copy:
    src: files/ansible_rsa.pub
    dest: /home/cephuser/.ssh/id_rsa.pub
    owner: cephuser
    group: cephuser
    mode: 0644

- name: Copy authorized_keys file
  copy:
    src: /home/cephuser/.ssh/id_rsa.pub
    dest: /home/cephuser/.ssh/authorized_keys
    remote_src: yes
    owner: cephuser
    group: cephuser
    mode: 0600

- name: Check if known_hosts file exists
  stat:
    path: /home/cephuser/.ssh/known_hosts
  register: stat_result

- name: Scan and add SSH keys of the machines to known_hosts file
  shell: "ssh-keyscan ceph-{{ item }} >> /home/cephuser/.ssh/known_hosts"
  loop:
    - admin
    - osd1
    - osd2
    - osd3
    - mon1
    - mon2
    - mon3
    - client1
    - client2
  when: not stat_result.stat.exists

- name: Change known_hosts file owner
  file:
    path: /home/cephuser/.ssh/known_hosts
    owner: cephuser
    group: cephuser

- name: Add Ceph apt key
  apt_key:
    url: https://download.ceph.com/keys/release.asc

- name: Add Ceph repository
  apt_repository:
    repo: deb https://download.ceph.com/debian-pacific/ buster main
    filename: ceph

- name: Ensure needed packages are installed
  apt:
    update_cache: yes
    name:
    - apt-transport-https
    - binutils
    - binutils-common
    - binutils-x86-64-linux-gnu
    - ceph
    - ceph-base
    - ceph-common
    - ceph-deploy
    - ceph-mds
    - ceph-mgr
    - ceph-mon
    - ceph-osd
    - cryptsetup-bin
    - dnsutils
    - gnupg
    - libbabeltrace1
    - libbinutils
    - libcephfs2
    - libcurl4
    - libdw1
    - libgoogle-perftools4
    - libibverbs1
    - libjs-jquery
    - libleveldb1d
    - liblttng-ust-ctl4
    - liblttng-ust0
    - liblua5.3-0
    - libnghttp2-14
    - libnl-3-200
    - libnl-route-3-200
    - liboath0
    - libparted2
    - libpython3.7
    - librabbitmq4
    - librados2
    - libradosstriper1
    - librbd1
    - librdkafka1
    - librdmacm1
    - librgw2
    - librtmp1
    - libsnappy1v5
    - libssh2-1
    - libtcmalloc-minimal4
    - libunwind8
    - liburcu6
    - lvm2
    - parted
    - psmisc
    - python-pastedeploy-tpl
    - python3-bcrypt
    - python3-bs4
    - python3-cephfs
    - python3-cherrypy3
    - python3-dateutil
    - python3-distutils
    - python3-lib2to3
    - python3-logutils
    - python3-mako
    - python3-openssl
    - python3-paste
    - python3-pastedeploy
    - python3-pecan
    - python3-prettytable
    - python3-rados
    - python3-rbd
    - python3-rgw
    - python3-simplegeneric
    - python3-singledispatch
    - python3-soupsieve
    - python3-tempita
    - python3-waitress
    - python3-webob
    - python3-webtest
    - python3-werkzeug
    - radosgw
    - xfsprogs
